### ISSUE TITLE
Can't load .tat files from the EditorDock

### ISSUE THREAD

**Issue by rmazzier** [MicheleLambertucci/tool-assisted-testing-for-godot#4] opened 2018-11-19 14:30 UTC
**Steps to reproduce:**
1) Create new .tat file and save it (I saved it in `"res://tatfiles/test1.tat"`);
2) Click "Load" button on the EditorDock, enter the filepath and the File Name in the corresponding prompts;
3) Load button remains greyed out

![image](https://user-images.githubusercontent.com/34507088/48713640-28541b80-ec11-11e8-9217-ca865cf9334e.png)

**Comment by MicheleLambertucci** [comment] 2018-11-19 14:41
If you resize the dialog you should see your files. Than select the file you want to load.

Closing as duplicate of #3

**Closed by MicheleLambertucci** 2018-11-19 14:41 UTC
Labels: duplicate
